### ISSUE TITLE
Failed to connect to the session server - retMsg: 'param \'uid\' not exist

### ISSUE THREAD

**Issue by craftingmod** [yoo2001818/node-ncc-es6#1]
![screen shot 2015-12-02 at 11 08 54 pm](https://cloud.githubusercontent.com/assets/9389278/11532854/fea506e0-9949-11e5-8840-c25e2dcf9870.png)

**Comment by yoo2001818** [comment]
https://github.com/craftingmod/node-ncc-es6/blob/8b57ffcd6aa8b74d40432a6fde97987fa5719e77/test/session.js#L34

``` diff
  credentials = new Credentials(result.username,result.password);
+ session.credentials = credentials;
  main();
```

`Session`은 `Credentials` 객체랑 묶여 있어서 credentials를 새로 만들 때 session도 업데이트 해줘야 해요.
